Neos:
  Neos:
    nodeTypes:
      presets:
        properties:
          'myNamespace':
            'rangeEditor':
              type: integer
              defaultValue: 12
              ui:
                inspector:
                  editor: Neos.Neos/Inspector/Editors/RangeEditor
                  editorOptions:
                    disabled: true
                    minLabel: 'Minimum'
                    maxLabel: 'Maximum'
                    min: 0
                    max: 100
                    step: 5
                    unit: px
